Make timer component
vectoscalar/react-native-vs-animated-component pull request #11
Opened 2024-07-16 12:30 UTC by chehak-vs

https://github.com/user-attachments/assets/75f406c5-3546-4adc-973e-64fa63d74abf

2024-07-19 09:07 UTC, divyanshu-srivastava-vs commented on AnimatedComponents/src/components/timer/Timer.tsx
> +        setTimeLeft(prev => (prev > 0 ? prev - 1 : 0))
we try avoiding states in animation. as well as timeout's/ interval

we can do instead
```  useEffect(() => {
    reanimatedTimer.value = withTiming(0, { duration: duration * 1000, easing: ReanimatedEasing.linear })

    return () => {
      reanimatedTimer.value = 1
    }
  }, [])


  ```

2024-07-19 09:10 UTC, divyanshu-srivastava-vs commented on AnimatedComponents/src/components/timer/Timer.tsx
> +    width: `${progress.value * 100}%`,
don't animated width. Instead use translate and overflow

2024-07-19 10:56 UTC, divyanshu-srivastava-vs commented
<img width="313" alt="image" src="https://github.com/user-attachments/assets/8d6b580f-4841-4c77-b31a-59712a213fac">


a line is coming in linear progress

2024-07-19 12:41 UTC, divyanshu-srivastava-vs requested changes

2024-07-19 12:41 UTC, divyanshu-srivastava-vs commented on AnimatedComponents/src/components/timer/Timer.tsx
> +  circularTimerStrokeColor?: string
dont take two props `linearTimerColor` and `circularTimerStrokeColor` instead use a prop name `strokeColor`

2024-07-19 12:41 UTC, divyanshu-srivastava-vs commented on AnimatedComponents/src/components/timer/Timer.tsx
> +  timerType: TimerPreset
timerType -> type

2024-07-19 12:41 UTC, divyanshu-srivastava-vs commented on AnimatedComponents/src/components/timer/Timer.tsx
> +  totalDurationInSeconds: number
duration

2024-07-19 12:41 UTC, divyanshu-srivastava-vs commented on AnimatedComponents/src/components/timer/Timer.tsx
> +  const [timeLeft, setTimeLeft] = useState(totalDurationInSeconds)
it will be removed

2024-07-19 12:41 UTC, divyanshu-srivastava-vs commented on AnimatedComponents/src/components/timer/Timer.tsx
> +        <Text style={styles.timeLeftTextCircular}>{formatTime(timeLeft)}</Text>
make a boolean prop which will control whether to show or not for both linear and circular

2024-07-19 12:41 UTC, divyanshu-srivastava-vs commented on AnimatedComponents/src/components/timer/Timer.tsx
> +  const [isPaused, setIsPaused] = useState(false)
try using a single state if possible for isRunning and isPaused.

2024-07-22 07:45 UTC, divyanshu-srivastava-vs commented
<img width="320" alt="image" src="https://github.com/user-attachments/assets/38a467e3-59fc-48df-a990-954e80771206">
its not looking as expected

2024-07-22 07:47 UTC, divyanshu-srivastava-vs commented on AnimatedComponents/App.tsx
> +      <Timer duration={10} type={TimerPreset.Linear} controls={true} />
<Timer duration={10} type={TimerPreset.Linear} controls />

2024-07-22 07:48 UTC, divyanshu-srivastava-vs commented on AnimatedComponents/src/components/timer/Timer.tsx
> +          startAnimation(duration * 1000)
'startAnimation' was used before it was defined.eslint[@typescript-eslint/no-use-before-define](https://typescript-eslint.io/rules/no-use-before-define)

2024-07-22 07:50 UTC, divyanshu-srivastava-vs commented on AnimatedComponents/src/components/timer/Timer.tsx
> +          startAnimation(duration * 1000)
never call a function or variable before its defination

2024-07-22 08:31 UTC, divyanshu-srivastava-vs commented
<img width="306" alt="image" src="https://github.com/user-attachments/assets/2e4112e1-5883-4891-986e-3bfb674ce1d6">

a line coming in linear in unfilled space. can u please check that?

2024-07-22 13:26 UTC, divyanshu-srivastava-vs commented
1. Pause bug (show play/pause at once)
2. duration-> two variable with same name.
3. resolve conflicts

2024-07-23 08:19 UTC, divyanshu-srivastava-vs commented
1. Play / pause icons are not at same position. Please check.

2024-07-23 08:20 UTC, divyanshu-srivastava-vs commented
reset functionality not working

2024-07-24 05:59 UTC, chehak-vs commented
> reset functionality not working

It is working. Please see the below video:
https://github.com/user-attachments/assets/f8e939fb-7d81-4e1b-a75f-99142bc4dd1f

2024-07-24 08:23 UTC, merged